name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.setup-node.outputs.node-version }}
    steps:
      - name: Set up Node.js
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

  test-frontend:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ needs.setup.outputs.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ needs.setup.outputs.node-version }}

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run frontend Jest tests
        run: npm test
        working-directory: ./frontend

  test-backend:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ needs.setup.outputs.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ needs.setup.outputs.node-version }}

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Run backend Jest tests
        run: npm test
        working-directory: ./backend
