on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - "backend/**"
      - "**.yml"
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"
      - "backend/**"
      - "**.yml"

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
        working-directory: ./frontend
      - run: |
          npm run lint
          npm run build
        working-directory: ./frontend

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: |
          pip install -r requirements.txt
        working-directory: ./backend
      - run: pip install flake8
      - run: |
          flake8 .
        working-directory: ./backend
      - run: |
          # Add commands to run your tests, e.g., pytest
          pytest
        working-directory: ./backend

  database-migrations:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - run: |
          # Command to apply database migrations, adjust as necessary
          # This step might require setting up a test database
          echo "Apply database migrations here"
